
EMPTY_NAME = 0
NO_ACRONYMN = "NO_ACR"
STOPWORDS = ['COM', 'SEM', 'DE', 'DA', 'MG']
NOT_FOUND = "NOT FOUND"

PROD_CODE_INDEX = 0
PROD_NAME_FORMATTED_INDEX = 2
PROD_NAME_COMPLETE_INDEX = 3
PROD_PRES_INDEX = 4
PROD_LAB_INDEX = 5
